layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  facebook: prasuna.reddy.9
  hackerrank: prasuna_16
  instagram: i_m_prasuna
  linkedin: prasuna-pulivendula-175263176
  telegram: suna_xp
  twitter: prasunareddy8

topics:
  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/isocpp/logos/master/cpp_logo.png
    description: Problem solving and competitive programming in C++.

  - name: Flask
    web_url: https://github.com/topics/flask
    image_url: https://www.todesktop.com/images/1c2437c139969ae8e4100b477fb824f1.svg
    description: Web development using Flask.

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIcAAACHCAMAAAALObo4AAAAwFBMVEX////loijxvybs7e4AAAD027wTExPywSbjnAAFBwjmpCjttCfkoCjkmQDvuQDwvRX99d700HXr6OLr4tLs8vjloCAwMDBJSUn9+OxtbW309fXzylTnt2/pyqBbXFzknhSJiYn+/PYZGRrnqDnrtmLpqyjz1azpsFf24se8vLzk5OSBgYHtwoXvyJLx0aH46dX44q766b3779D43Zv11IHorEfp0a3yxUfU1NQ/Pz+YmJgmJyempqbrrADzzGD22I/yUs50AAAHT0lEQVR4nO2afVfiOBTGC4ithYK8xKnCmGHbhe4IKmhlZ2dHv/+32pak5Ka5QZIKztnD88ccZ04bf5OX5740jnPSSf9v3TRyZT80ZN0cmeP2LNP5d+f7may/jsxxfXZxcXbVyDjOoU4cBccnr4vzjYGcXX/Ldff3Z3FkO3bDcXvsk1LmyH7cgPz4bI4Gn5HrT+Zwbs4YyN0ncziNq+PPyA2TxOF8P7/YgPxzNIxvt0w/JY5sadjp/fdYHNdFILkofOyPXD+vzo8Lkq9HIcbBfi5c9VhbROWQ48vxOIB+ivko0I7Fcffji9BtIzuyX6B+fIaHnHTSSb+NJs1DaWLEEQbeYRSEZhxR7TCKzDgmM3IQDDIzW5dJfCCO2IzDGR+IY2yG4cwPxDE35FjQ/Qf39xF7lC4MOe7352i3XLf+jtw657g35Ei8/eej9S5GpvbmUS8x5HgITObjXQq3xTiCB0OOEOegAaJfHVxdhMPMxjIDQTnoeIDpElX4inAY2ofjoBze12FDla7r0QMT8ifnMMVw0H3qvZhwPHXEfHAOz5gjwozMSxAMLccj4GD+QSJjDjTABH0TjqXKERtzzDEj84w4VoKjzjioqa1rjD0y4ghVDlNbd5wpslHJDMPYi4PP59SYo4lxxGYc23PrtjhH05gjQdaFjI04JuuyjVHT8JIFGOS8kDlmH3qO126JwzcNL3imTBeAYyikG0PhMMySdRzQ1vvRLPV9mlUCmzjXrY96vbenx+USjPH8ARyTVF0Yryk4BgHJlP8rj/vdXBkR+FVvWw5m6yQ1DnOOg1QOwUCsyos4T1L+0bkUQzwJDra/ZuYYKIewsSFIHGWOlRhiG2Bcv23NgVQOAdilCx0H2CArwcHmw7RqyIUEmEBsjyEoLCSO7pMY4nLLwe3DPLygxk7BsY11HG9iCGHsPPswt3WMg0SAY6bjeAZjcA634DC3dSxjJzHgSHUcPT2HcbaeS83YKbD1vl/TcLwCj3BlGzPO1jccyrpAW+97Go76GnCMuhKHZ8WhnFuYJfcDHUcdcDzLHL4Nh2rsXlMc20TL4Y6EeOCvYutIS4iKbB3aenk+ukJ1mcOwGcSlZOwEhJeveg5EnMM8W8+lGDvIkofQbffmsLF1xNghR+zRQuRXV6eCw7pqyFWuHEgKwtx8LNTTqkhQ+f4yrxpylY2dpHhWqE0LRUJWIbyoLSHJ1qH0Q4xkDvNsPVc5wJCxMQffwLbNIKZygJGy9f04OpKdWoUXR2nF4E0YEw47DIUDbcLs4ijyIOtmEFPp3OJNmF0cPC/k2XqNWnKUAh3ehNnFwfPkIktOLTlKxo43YXZxPEoc1M7WFWP3jTmKOqqSrZeNnaSDPq5QEhjgTeaws3W1FaP7lNBygTpggGeJwypbxzg0kvvrkIP1HbbZqS0H1hLCJHG44v1JwcEes2gGMT34u38/xtEdAY61ZKc1u/CitmKo+Ayr5wDlXOhKHBZNmIJDMpDoq5Cv5VDL26L5Yc0hG2qWjonUR8qhJY5HhINXDbYYpVYM8LHhmGo4kPbHtmqw5pArB0+Trms5loWtV6kackn/a11XqrQualvK5bvcNryUP54Gicg/JIuT/AO06bitF80g00+mQnLGDvOgRDcfa3Aoeh+RreeSjR3mhQPdeYEc7DthpWYQk5yxwzbMgBCUo7sGr48kDstsPZecsUt1w31ao7TE0emuX4F9lGzdNlvPOeQEZAbrucagOfcCL5+XnKPb6ayfVtKvCnlVWXzzqMBRkzjSUr4+HPZfxlFAW53O6Hmpvl2HNmYfXsotIVhni2npDxa9xxBrsKz4clVpBnEO2VDxr4QNXZ297EocpjdyoEoZ+wDl0OXJSzm82Ntp+XYOMeMovjbw6sU2W88lZ+xUU9BpXi6qBv6ybbaeSw4wXjJEK1zNy3ITpkJ4KRs7ieZJv6GiIC9OwmWv8NjKtq60Ynwa+OP7QXlWlNdWb6/gNkxlW0dv5xAaeOMXiUVmeMwZwA2U6rauvyXkRbPFYLtE4vFVb12H14JgeKlgH5rbOXxaovG0v5kW9ujl02uZAdq6bRPmHY4NixfQRbOf+enlsicvxkdz+O9dM6Q0ip+VxVA5iF+JY59rqGRnf71oBtlXDbnQ2zll7e7zV2zCfDRHFVvf89qlhsN13XqLtwprXhVb37MVg3Ewhna7XXBUsfU9r3+WODZ/a/m1LcNmXWybMJzDdF3YYvhtCSITqRJeskBX2+Pgbjk2DG2FIcewbgYxhTPivUvCOLI/8h2BPUC8WlwlzGWaPEzjIKA7WTZ9S2wxNgw0COJptdkolCxiLyBallarpWXw4sXHMDBNwuY40i1Ru4YtR/Z0Om6ilU1Flof7NNgxLZCBBEE6ffh4hq2SeRrs3rmEeN5sXs0u9tEkvI8jqtm5hNI0nh5gMTQsycJntb48EUG6SI7FsGXJdq5YopxhXi2GVEDJdm6+RFlSNjveYuAKk3lWXlV0y5N+V/0HcGHP1n3OLBYAAAAASUVORK5CYII=
    description: Building interactive web applications.

schools:
  - name: National Institute of Technology, Andhra Pradesh (2018-2022)
    web_url: https://en.wikipedia.org/wiki/National_Institute_of_Technology,_Andhra_Pradesh
    image_url: https://upload.wikimedia.org/wikipedia/en/3/36/NIT_Andhra_Pradesh.png
    description: Undergraduate in Computer Science and Engineering. CGPA 9.82/10

  - name: Sri Chaitanya Junior College (2016-2018)
    web_url: https://srichaitanya.net/
    image_url: https://srichaitanya.net/wp-content/uploads/2020/04/srichaitana_logo_hires.png
    description: Stream - Mathematics, Physics and Chemistry.
