layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  facebook: prasuna.pulivendula.9
  hackerrank: prasuna_16
  instagram: i_m_prasuna
  linkedin: prasuna-pulivendula-175263176
  telegram: suna_xp
  twitter: prasunareddy8

topics:
  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/isocpp/logos/master/cpp_logo.png
    description: Problem solving and competitive programming in C++.

  - name: Flask
    web_url: https://github.com/topics/flask
    image_url: https://www.todesktop.com/images/1c2437c139969ae8e4100b477fb824f1.svg
    description: Web development using Flask.

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    description: Building interactive web applications.

schools:
  - name: National Institute of Technology, Andhra Pradesh (2018-2022)
    web_url: https://en.wikipedia.org/wiki/National_Institute_of_Technology,_Andhra_Pradesh
    image_url: https://upload.wikimedia.org/wikipedia/en/3/36/NIT_Andhra_Pradesh.png
    description: Undergraduate in Computer Science and Engineering. CGPA 9.82/10

  - name: Sri Chaitanya Junior College (2016-2018)
    web_url: https://srichaitanya.net/
    image_url: https://srichaitanya.net/wp-content/uploads/2020/04/srichaitana_logo_hires.png
    description: Stream - Mathematics, Physics and Chemistry.
